DOMAIN = "myleonardo"
BASE_URL = "https://myleonardo.western.it"
CONF_API_KEY = "api_key"
CONF_PLANT_KEY = "plant_key"

CONF_ENABLE_REALTIME_SENSORS = "enable_realtime_sensors"
CONF_ENABLE_ENERGY_SENSORS = "enable_energy_sensors"
CONF_ENABLE_ADVANCED_SENSORS = "enable_advanced_sensors"
CONF_REALTIME_SCAN_INTERVAL = "realtime_scan_interval"
CONF_ENERGY_SCAN_INTERVAL = "energy_scan_interval"
CONF_ADVANCED_SCAN_INTERVAL = "advanced_scan_interval"

DEFAULT_ENABLE_REALTIME_SENSORS = True
DEFAULT_ENABLE_ENERGY_SENSORS = True
DEFAULT_ENABLE_ADVANCED_SENSORS = True
DEFAULT_REALTIME_SCAN_INTERVAL = 30
DEFAULT_ENERGY_SCAN_INTERVAL = 300
DEFAULT_ADVANCED_SCAN_INTERVAL = 120

MIN_REALTIME_SCAN_INTERVAL = 5
MIN_ENERGY_SCAN_INTERVAL = 20
MIN_ADVANCED_SCAN_INTERVAL = 20
