from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfTemperature,
)


@dataclass
class MyLeonardoSensorDescription(
    SensorEntityDescription
):
    """Describes how one API field should become a Home Assistant sensor."""

    unit: str | None = None
    source: str = ""
    source_key: str | None = None
    scale: float = 1
    value_type: str = "number"
    enabled_default: bool = True


class MyLeonardoSensorDescriptions:
    """Sensor definitions grouped by the API endpoint they come from."""

    MODBUS = [
        MyLeonardoSensorDescription(
            key="pv_power",
            name="PV Power",
            translation_key="modbus_pv_power",
            source="modbus",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="home_power",
            name="Home Power",
            translation_key="modbus_home_power",
            source="modbus",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="grid_power",
            name="Grid Power",
            translation_key="modbus_grid_power",
            source="modbus",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="grid_import_power",
            name="Grid Import Power",
            translation_key="modbus_grid_import_power",
            source="modbus",
            source_key="grid_power",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            value_type="positive",
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="grid_export_power",
            name="Grid Export Power",
            translation_key="modbus_grid_export_power",
            source="modbus",
            source_key="grid_power",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            value_type="negative_abs",
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="grid_l1_power",
            name="Grid L1 Power",
            translation_key="modbus_grid_l1_power",
            source="modbus",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="grid_l2_power",
            name="Grid L2 Power",
            translation_key="modbus_grid_l2_power",
            source="modbus",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="grid_l3_power",
            name="Grid L3 Power",
            translation_key="modbus_grid_l3_power",
            source="modbus",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="battery_power",
            name="Battery Power",
            translation_key="modbus_battery_power",
            source="modbus",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="battery_charge_power",
            name="Battery Charge Power",
            translation_key="modbus_battery_charge_power",
            source="modbus",
            source_key="battery_power",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            value_type="positive",
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="battery_discharge_power",
            name="Battery Discharge Power",
            translation_key="modbus_battery_discharge_power",
            source="modbus",
            source_key="battery_power",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            value_type="negative_abs",
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="battery_soc",
            name="Battery SOC",
            translation_key="modbus_battery_soc",
            source="modbus",
            device_class=SensorDeviceClass.BATTERY,
            unit=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="battery_voltage",
            name="Battery Voltage",
            translation_key="modbus_battery_voltage",
            source="modbus",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="battery_temperature",
            name="Battery Temperature",
            translation_key="modbus_battery_temperature",
            source="modbus",
            device_class=SensorDeviceClass.TEMPERATURE,
            unit=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="ac_input_voltage",
            name="AC Input Voltage",
            translation_key="modbus_ac_input_voltage",
            source="modbus",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="ac_output_voltage",
            name="AC Output Voltage",
            translation_key="modbus_ac_output_voltage",
            source="modbus",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="pv_energy",
            name="PV Energy Total",
            translation_key="modbus_pv_energy_total",
            source="modbus",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        MyLeonardoSensorDescription(
            key="home_energy",
            name="Home Energy Total",
            translation_key="modbus_home_energy_total",
            source="modbus",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        MyLeonardoSensorDescription(
            key="battery_charge_energy",
            name="Battery Charge Energy Total",
            translation_key="modbus_battery_charge_energy_total",
            source="modbus",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        MyLeonardoSensorDescription(
            key="grid_import_energy",
            name="Grid Import Energy Total",
            translation_key="modbus_grid_import_energy_total",
            source="modbus",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="grid_export_energy",
            name="Grid Export Energy Total",
            translation_key="modbus_grid_export_energy_total",
            source="modbus",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="battery_discharge_energy",
            name="Battery Discharge Energy Total",
            translation_key="modbus_battery_discharge_energy_total",
            source="modbus",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            enabled_default=False,
        ),
    ]

    REALTIME = [
        MyLeonardoSensorDescription(
            key="PacPV",
            name="Production Power",
            translation_key="realtime_production",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="PacHome",
            name="Home Power",
            translation_key="realtime_home_consumption",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="PacGrid",
            name="Grid Power",
            translation_key="realtime_grid_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="grid_import_power",
            name="Grid Import Power",
            translation_key="realtime_grid_import_power",
            source="realtime",
            source_key="PacGrid",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            value_type="positive",
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="grid_export_power",
            name="Grid Export Power",
            translation_key="realtime_grid_export_power",
            source="realtime",
            source_key="PacGrid",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            value_type="negative_abs",
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="Pbat",
            name="Battery Power",
            translation_key="realtime_battery_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="battery_charge_power",
            name="Battery Charge Power",
            translation_key="realtime_battery_charge_power",
            source="realtime",
            source_key="Pbat",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            value_type="positive",
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="battery_discharge_power",
            name="Battery Discharge Power",
            translation_key="realtime_battery_discharge_power",
            source="realtime",
            source_key="Pbat",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
            value_type="negative_abs",
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="Pload",
            name="Load Power",
            translation_key="realtime_load_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Ppwm",
            name="PWM Power",
            translation_key="realtime_pwm_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="SoC",
            name="Battery SOC",
            translation_key="realtime_battery_soc",
            source="realtime",
            device_class=SensorDeviceClass.BATTERY,
            unit=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Tbat",
            name="Battery Temperature",
            translation_key="realtime_battery_temperature",
            source="realtime",
            device_class=SensorDeviceClass.TEMPERATURE,
            unit=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="walc_pread",
            name="Wallbox Power",
            translation_key="realtime_wallbox_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="walc_energy",
            name="Wallbox Energy",
            translation_key="realtime_wallbox_energy",
            source="realtime",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Rtime",
            name="Updated",
            translation_key="realtime_updated",
            source="realtime",
            device_class=SensorDeviceClass.TIMESTAMP,
            value_type="timestamp",
            enabled_default=False,
        ),
    ]

    ENERGY = [
        MyLeonardoSensorDescription(
            key="EacPV",
            name="Solar Energy Today",
            translation_key="energy_solar_energy_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacHome",
            name="Home Consumption Today",
            translation_key="energy_home_consumption_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacGridIn",
            name="Grid Import Today",
            translation_key="energy_grid_import_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacGridOut",
            name="Grid Export Today",
            translation_key="energy_grid_export_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Einbat",
            name="Battery Charged Today",
            translation_key="energy_battery_charged_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Eoutbat",
            name="Battery Discharged Today",
            translation_key="energy_battery_discharged_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Epwm",
            name="PWM Today",
            translation_key="energy_pwm_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="Eload",
            name="Load Today",
            translation_key="energy_load_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Stime",
            name="Bucket Date",
            translation_key="energy_bucket_date",
            source="energy",
            device_class=SensorDeviceClass.DATE,
            value_type="date",
            enabled_default=False,
        ),
    ]

    ENERGY_MONTHLY = [
        MyLeonardoSensorDescription(
            key="EacPV",
            name="Solar Energy This Month",
            translation_key="energy_solar_energy_month",
            source="energy_monthly",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacHome",
            name="Home Consumption This Month",
            translation_key="energy_home_consumption_month",
            source="energy_monthly",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacGridIn",
            name="Grid Import This Month",
            translation_key="energy_grid_import_month",
            source="energy_monthly",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacGridOut",
            name="Grid Export This Month",
            translation_key="energy_grid_export_month",
            source="energy_monthly",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Einbat",
            name="Battery Charged This Month",
            translation_key="energy_battery_charged_month",
            source="energy_monthly",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Eoutbat",
            name="Battery Discharged This Month",
            translation_key="energy_battery_discharged_month",
            source="energy_monthly",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Epwm",
            name="PWM This Month",
            translation_key="energy_pwm_month",
            source="energy_monthly",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="Eload",
            name="Load This Month",
            translation_key="energy_load_month",
            source="energy_monthly",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Stime",
            name="Month Bucket Date",
            translation_key="energy_month_bucket_date",
            source="energy_monthly",
            device_class=SensorDeviceClass.DATE,
            value_type="date",
            enabled_default=False,
        ),
    ]

    ADVANCED = [
        MyLeonardoSensorDescription(
            key="avgPacPV",
            name="Average Production",
            translation_key="advanced_average_production",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPacHome",
            name="Average Home Consumption",
            translation_key="advanced_average_home_consumption",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPacGrid",
            name="Average Grid Power",
            translation_key="advanced_average_grid_power",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPbat",
            name="Average Battery Power",
            translation_key="advanced_average_battery_power",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPload",
            name="Average Load Power",
            translation_key="advanced_average_load_power",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPpwm",
            name="Average PWM Power",
            translation_key="advanced_average_pwm_power",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Vbat",
            name="Battery Voltage",
            translation_key="advanced_battery_voltage",
            source="advanced",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Ibat",
            name="Battery Current",
            translation_key="advanced_battery_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Iload",
            name="Load Current",
            translation_key="advanced_load_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Ipwm",
            name="PWM Current",
            translation_key="advanced_pwm_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="nCicli",
            name="Battery Cycles",
            translation_key="advanced_battery_cycles",
            source="advanced",
            state_class=SensorStateClass.TOTAL,
        ),
        MyLeonardoSensorDescription(
            key="Tbat",
            name="Battery Temperature",
            translation_key="advanced_battery_temperature",
            source="advanced",
            device_class=SensorDeviceClass.TEMPERATURE,
            unit=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Tint",
            name="Internal Temperature",
            translation_key="advanced_internal_temperature",
            source="advanced",
            device_class=SensorDeviceClass.TEMPERATURE,
            unit=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="SoC",
            name="Battery SOC",
            translation_key="advanced_battery_soc",
            source="advanced",
            device_class=SensorDeviceClass.BATTERY,
            unit=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="VacIn",
            name="AC Input Voltage",
            translation_key="advanced_ac_input_voltage",
            source="advanced",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="IacIn",
            name="AC Input Current",
            translation_key="advanced_ac_input_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="VacOut",
            name="AC Output Voltage",
            translation_key="advanced_ac_output_voltage",
            source="advanced",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="IacOut",
            name="AC Output Current",
            translation_key="advanced_ac_output_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="FacIn",
            name="AC Input Frequency",
            translation_key="advanced_ac_input_frequency",
            source="advanced",
            device_class=SensorDeviceClass.FREQUENCY,
            unit="Hz",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="FacOut",
            name="AC Output Frequency",
            translation_key="advanced_ac_output_frequency",
            source="advanced",
            device_class=SensorDeviceClass.FREQUENCY,
            unit="Hz",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Stime",
            name="Bucket Time",
            translation_key="advanced_bucket_time",
            source="advanced",
            device_class=SensorDeviceClass.TIMESTAMP,
            value_type="timestamp",
            enabled_default=False,
        ),
    ]

    ADVANCED_COMPLETE = [
        MyLeonardoSensorDescription(
            key="SoH",
            name="Battery SOH",
            translation_key="advanced_complete_battery_soh",
            source="advanced_complete",
            device_class=SensorDeviceClass.BATTERY,
            unit=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="VEoC",
            name="Battery End-of-Charge Voltage",
            translation_key="advanced_complete_battery_eoc_voltage",
            source="advanced_complete",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="PacInv",
            name="Inverter Power",
            translation_key="advanced_complete_inverter_power",
            source="advanced_complete",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="VbatInv",
            name="Inverter Battery Voltage",
            translation_key="advanced_complete_inverter_battery_voltage",
            source="advanced_complete",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="IbatInv",
            name="Inverter Battery Current",
            translation_key="advanced_complete_inverter_battery_current",
            source="advanced_complete",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="FlagWRM",
            name="WRM Flag",
            translation_key="advanced_complete_wrm_flag",
            source="advanced_complete",
        ),
        MyLeonardoSensorDescription(
            key="FlagWBM",
            name="WBM Flag",
            translation_key="advanced_complete_wbm_flag",
            source="advanced_complete",
        ),
        MyLeonardoSensorDescription(
            key="FlagWRD",
            name="WRD Flag",
            translation_key="advanced_complete_wrd_flag",
            source="advanced_complete",
        ),
        MyLeonardoSensorDescription(
            key="FlagLK3",
            name="LK3 Flag",
            translation_key="advanced_complete_lk3_flag",
            source="advanced_complete",
        ),
        MyLeonardoSensorDescription(
            key="SystemChargeWRD",
            name="WRD System Charge",
            translation_key="advanced_complete_wrd_system_charge",
            source="advanced_complete",
            unit=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
        ),
    ]
