from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfTemperature,
)


@dataclass
class MyLeonardoSensorDescription(
    SensorEntityDescription
):
    """Describes how one API field should become a Home Assistant sensor."""

    unit: str | None = None
    source: str = ""
    scale: float = 1
    value_type: str = "number"
    enabled_default: bool = True


class MyLeonardoSensorDescriptions:
    """Sensor definitions grouped by the API endpoint they come from."""

    REALTIME = [
        MyLeonardoSensorDescription(
            key="PacPV",
            name="Realtime Production",
            translation_key="realtime_production",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="PacHome",
            name="Realtime Home Consumption",
            translation_key="realtime_home_consumption",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="PacGrid",
            name="Realtime Grid Power",
            translation_key="realtime_grid_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Pbat",
            name="Realtime Battery Power",
            translation_key="realtime_battery_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Pload",
            name="Realtime Load Power",
            translation_key="realtime_load_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Ppwm",
            name="Realtime PWM Power",
            translation_key="realtime_pwm_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="SoC",
            name="Realtime Battery SOC",
            translation_key="realtime_battery_soc",
            source="realtime",
            device_class=SensorDeviceClass.BATTERY,
            unit=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Tbat",
            name="Realtime Battery Temperature",
            translation_key="realtime_battery_temperature",
            source="realtime",
            device_class=SensorDeviceClass.TEMPERATURE,
            unit=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="walc_pread",
            name="Realtime Wallbox Power",
            translation_key="realtime_wallbox_power",
            source="realtime",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="walc_energy",
            name="Realtime Wallbox Energy",
            translation_key="realtime_wallbox_energy",
            source="realtime",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Rtime",
            name="Realtime Updated",
            translation_key="realtime_updated",
            source="realtime",
            device_class=SensorDeviceClass.TIMESTAMP,
            value_type="timestamp",
            enabled_default=False,
        ),
    ]

    ENERGY = [
        MyLeonardoSensorDescription(
            key="EacPV",
            name="Energy Solar Energy Today",
            translation_key="energy_solar_energy_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacHome",
            name="Energy Home Consumption Today",
            translation_key="energy_home_consumption_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacGridIn",
            name="Energy Grid Import Today",
            translation_key="energy_grid_import_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="EacGridOut",
            name="Energy Grid Export Today",
            translation_key="energy_grid_export_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Einbat",
            name="Energy Battery Charged Today",
            translation_key="energy_battery_charged_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Eoutbat",
            name="Energy Battery Discharged Today",
            translation_key="energy_battery_discharged_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Epwm",
            name="Energy PWM Today",
            translation_key="energy_pwm_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
            enabled_default=False,
        ),
        MyLeonardoSensorDescription(
            key="Eload",
            name="Energy Load Today",
            translation_key="energy_load_today",
            source="energy",
            device_class=SensorDeviceClass.ENERGY,
            unit=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            scale=0.001,
        ),
        MyLeonardoSensorDescription(
            key="Stime",
            name="Energy Bucket Date",
            translation_key="energy_bucket_date",
            source="energy",
            device_class=SensorDeviceClass.DATE,
            value_type="date",
            enabled_default=False,
        ),
    ]

    ADVANCED = [
        MyLeonardoSensorDescription(
            key="avgPacPV",
            name="Advanced Average Production",
            translation_key="advanced_average_production",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPacHome",
            name="Advanced Average Home Consumption",
            translation_key="advanced_average_home_consumption",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPacGrid",
            name="Advanced Average Grid Power",
            translation_key="advanced_average_grid_power",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPbat",
            name="Advanced Average Battery Power",
            translation_key="advanced_average_battery_power",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPload",
            name="Advanced Average Load Power",
            translation_key="advanced_average_load_power",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="avgPpwm",
            name="Advanced Average PWM Power",
            translation_key="advanced_average_pwm_power",
            source="advanced",
            device_class=SensorDeviceClass.POWER,
            unit=UnitOfPower.WATT,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Vbat",
            name="Advanced Battery Voltage",
            translation_key="advanced_battery_voltage",
            source="advanced",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Ibat",
            name="Advanced Battery Current",
            translation_key="advanced_battery_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Iload",
            name="Advanced Load Current",
            translation_key="advanced_load_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Ipwm",
            name="Advanced PWM Current",
            translation_key="advanced_pwm_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="nCicli",
            name="Advanced Battery Cycles",
            translation_key="advanced_battery_cycles",
            source="advanced",
            state_class=SensorStateClass.TOTAL,
        ),
        MyLeonardoSensorDescription(
            key="Tbat",
            name="Advanced Battery Temperature",
            translation_key="advanced_battery_temperature",
            source="advanced",
            device_class=SensorDeviceClass.TEMPERATURE,
            unit=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Tint",
            name="Advanced Internal Temperature",
            translation_key="advanced_internal_temperature",
            source="advanced",
            device_class=SensorDeviceClass.TEMPERATURE,
            unit=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="SoC",
            name="Advanced Battery SOC",
            translation_key="advanced_battery_soc",
            source="advanced",
            device_class=SensorDeviceClass.BATTERY,
            unit=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="VacIn",
            name="Advanced AC Input Voltage",
            translation_key="advanced_ac_input_voltage",
            source="advanced",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="IacIn",
            name="Advanced AC Input Current",
            translation_key="advanced_ac_input_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="VacOut",
            name="Advanced AC Output Voltage",
            translation_key="advanced_ac_output_voltage",
            source="advanced",
            device_class=SensorDeviceClass.VOLTAGE,
            unit="V",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="IacOut",
            name="Advanced AC Output Current",
            translation_key="advanced_ac_output_current",
            source="advanced",
            device_class=SensorDeviceClass.CURRENT,
            unit="A",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="FacIn",
            name="Advanced AC Input Frequency",
            translation_key="advanced_ac_input_frequency",
            source="advanced",
            device_class=SensorDeviceClass.FREQUENCY,
            unit="Hz",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="FacOut",
            name="Advanced AC Output Frequency",
            translation_key="advanced_ac_output_frequency",
            source="advanced",
            device_class=SensorDeviceClass.FREQUENCY,
            unit="Hz",
            state_class=SensorStateClass.MEASUREMENT,
        ),
        MyLeonardoSensorDescription(
            key="Stime",
            name="Advanced Bucket Time",
            translation_key="advanced_bucket_time",
            source="advanced",
            device_class=SensorDeviceClass.TIMESTAMP,
            value_type="timestamp",
            enabled_default=False,
        ),
    ]
